COHERE_API_KEY = "cohere_cQEXcw6H6nGbKsc8CJuYgqjtgNqF9zYEytlmnvaH2Mi9X4"
DEEPL_API_KEY = "0d40f1a7-553b-44eb-9aab-837a828ca913:fx"
GROQ_API_KEY   = "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"
